### ISSUE TITLE
Cell Size Zoom level

### ISSUE THREAD

**Issue by zaabs** [sebsebmc/starlink-coverage#11] opened 2020-06-21 20:38 UTC
Could we get smaller Cells so we can get more accurate coverage

**Comment by sebsebmc** [comment] 2020-06-21 20:46
The data is generated with cell sizes about 1/50th of what you see in the visualization. Finding a way to visualize this without massive performance issues is going to be the hard part.

However, I'm closing this as a duplicate of #4

**Closed by sebsebmc** 2020-06-21 20:46 UTC
